services:
  db:
    image: postgres:16
    container_name: pokedex-db
    environment:
      POSTGRES_USER: pokemon
      POSTGRES_PASSWORD: pokemon
      POSTGRES_DB: pokedex
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pokemon -d pokedex"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db-data:
